#!/bin/bash

# Get the some path - used to include other files 
SCRIPT_PATH=`dirname "$(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")"`
PARENT_PATH=`dirname "$SCRIPT_PATH"`
CONFIG_PATH="$SCRIPT_PATH/config"
BIN_PATH="$SCRIPT_PATH/bin"

# set some vars to references from one place
FUNCTIONS="$BIN_PATH/functions.sh"
UTILS="$BIN_PATH/utils.sh"

# import the functions
source "$FUNCTIONS"
source "$UTILS"

START_TIME=$(date +"%T")
print_comment "Started at $START_TIME"

# work out which version of mac os we are running needed 
# as the HOMEBREW_PREFIX needs to be set differently and 
# I want to control what to install depending on the OS
MAJOR_MAC_VERSION=$(sw_vers -productVersion | awk -F '.' '{print $1}')
MINOR_MAC_VERSION=$(sw_vers -productVersion | awk -F '.' '{print $2}')

if [ "$MAJOR_MAC_VERSION" == "10" ]; then
	if [ "$MINOR_MAC_VERSION" == "14" ]; then
		MAC_OS_NAME="mojave"
	elif [ "$MINOR_MAC_VERSION" == "15" ]; then
		MAC_OS_NAME="catalina"
	fi
elif [ "$MAJOR_MAC_VERSION" == "11" ]; then
	MAC_OS_NAME="bigsur"
else 
	MAC_OS_NAME="unknown"
fi


# shellcheck disable=SC2154
# Print out the failure when exiting the script
trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

# exit if there is an error
set -e


print_in_red "
###############################################################################

Your password (assuming you are setup as an admin) is need to install the 
latest Max OS updates and to ensure permssions on homebrew are setup correctly.

Please make sure you have read this script and are happy to provide 
your password.

###############################################################################

"

ask_for_confirmation "Do you want to continue?"
if answer_is_no; then 
	exit 0
fi

print_comment  "Using settings for $MAC_OS_NAME"
BREWFILE="$CONFIG_PATH/Brewfile"

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until the script has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

########################[ INSTALL depending on OS ]############################
RUNNING_SYSTEM=`uname -s`

# We're on a Mac, let's install and setup using homebrew.
if [ "$RUNNING_SYSTEM" == "Darwin" ]
then

########################[ Updating Mac OS ]####################################
# Update mac software
	echo "Updating mac os"
		sudo softwareupdate -i -a

########################[ Command line xcode ]#################################
	echo "Install Apple command line tools"
	COMMANDLINE_TOOLS="/Library/Developer/CommandLineTools"
	if [ ! -d "$COMMANDLINE_TOOLS" ]; then
		xcode-select --install
		echo "Commandline tools not found where expected, trying anyway"
	fi


########################[ Check homebrew is installed ]########################
	echo "Using homebrew to install software "
	# Set the install location for homebrew... use the default.
	if [ "$MAC_OS_NAME" == "bigsur" ]; then
		HOMEBREW_PREFIX="/opt/homebrew"
	else 
		HOMEBREW_PREFIX="/usr/local"
	fi

	if [ -d "$HOMEBREW_PREFIX" ]; then
		if ! [ -r "$HOMEBREW_PREFIX" ]; then
			sudo chown -R "$LOGNAME:admin" /usr/local
		fi
	else
		sudo mkdir "$HOMEBREW_PREFIX"
		sudo chflags norestricted "$HOMEBREW_PREFIX"
		sudo chown -R "$LOGNAME:admin" "$HOMEBREW_PREFIX"
	fi

	# Check to see if homebrew is installed, and if not then install it
	if ! command -v brew >/dev/null; then
		print_comment "Using $HOMEBREW_PREFIX for homebrew "
		echo "Installing Homebrew ..."
			#curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
			/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

			export PATH="$HOMEBREW_PREFIX/bin:$PATH"
	fi

	if brew list | grep -Fq brew-cask; then
		echo "Uninstalling old Homebrew-Cask ..."
		brew uninstall --force brew-cask
	fi

########################[ Install homebrew apps ]##############################
	echo "Updating Homebrew formulae ..."
	brew update --force 					 # https://github.com/Homebrew/brew/issues/1151
	echo "Updated forcefully"

	print_comment "Installing apps from Brewfile"
	# generic apps for all engineers
	if brew bundle --file="$BREWFILE"; then
		print_success "All items in Brewfile were installed successfully."
	else
		print_warning "Some items in Brewfile were not installed successfully."
	fi

########################[ Run user customisations ]############################
# run anything from the user local file, assuming the user wants it 
	ask_for_confirmation "Do you want it include customisations and preferences from $USER.local?"
	if answer_is_yes; then
		if [ -f "$USER.local" ]; then
			# shellcheck disable=SC1090
			sh "$USER.local"
		fi
	fi

########################[ OSX Customisations ]#################################
	# if [ -f "osx-customisations.sh" ]; then
	# echo "Customising OSX... (inspired by https://github.com/mathiasbynens/dotfiles)"
	# 	# shellcheck disable=SC1090
	#  	sh osx-customisations.sh
	# fi

###############################################################################
########################[ Linux Customisations ]###############################
elif [ "$RUNNING_SYSTEM" == "Linux" ]
then
	echo "Install for Linux"
	sh linux.sh
else
	fail "Unfortunately your system is not currently supported with this script"
fi


########################[ GIT ]################################################
# echo "Setup github account on machine"
#   sh git_config.sh

brew cleanup
rm -f -r /Library/Caches/Homebrew/*

END_TIME=$(date +"%T")

echo "Started at 	: $START_TIME"
echo "Ended at 	: $END_TIME"

echo "DONE!"
