#casks - for extra funtionality
tap "homebrew/bundle"
tap "thoughtbot/formulae"
tap "buo/cask-upgrade"                  # to upgrade all the apps installed by homebrew cask
tap "homebrew/core"
tap "homebrew/services"
tap "homebrew/cask-cask"
tap "universal-ctags/universal-ctags"

# Set applications directory
cask_args appdir: "/Applications"

# Unix tools
brew "universal-ctags", args: ["HEAD"]
brew "git"
brew "openssl"
brew "readline"     # Utilities that one needs....

# GitHub
brew "hub"

# Programming language prerequisites and package managers
brew "libyaml"              # should come after openssl
brew "coreutils"
brew "jq"

# development tools
cask "docker"           # docker - containerise all the things
cask "iterm2"           # item - terminal alternative
cask "postman"          # Postman - for API development and testing

# video viewer
cask "vlc"

# slack
cask "slack"

# we're GCP command line tools
cask "google-cloud-sdk"